name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  powershell-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run package tests
        shell: pwsh
        run: ./tests/test_package.ps1